[project]
name = "lsp-ruff"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "ruff>=0.12.4",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = []
select = [
    "E",
    "F",
    "W",
]
